package com.siriusif.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Order {
	private Long id;
	/**
	 * date of order
	 */
	private Date date;
	/**
	 * sum order include discountSum
	 */
	private BigDecimal sum;
	private String autor;
	private int discount;
//	private int status; ENUM
	/**
	 * number of table
	 */
	private int tableNum;
//	private String originalAutor;??????
	/**
	 * order was printed on a fiscal printer
	 */
	private boolean readOnly;
	/**
	 * order for return
	 */
	private boolean type;
	/**
	 * working date
	 */
	private Date workingDate;
	private Long workShift;
	private int nomerok;
	/**
	 * money from client
	 */
	private BigDecimal payed;
	/**
	 * paid with credit card
	 */
	private boolean isCard;
	/**
	 * number of order for workshift
	 */
	private int dailyId;
	private List<Suborder> suborders;

	public Order() {
		suborders = new ArrayList<Suborder>();
	}

	// use("",0,0)
	/*
	 * public void use(autor, tableNum, workShift){ this.autor = autor;
	 * this.tableNum = tableNum; this.workShift = workShift; //tableNum>0 //vvv
	 * }
	 */

	public boolean isValid() {
		if (tableNum > 0 && autor != null && workShift > 0) {
			return true;
		} else {
			return false;
		}
	}

	public void addSuborder(Suborder suborder) {
		suborder.setOrder(this);
		suborders.add(suborder);
	}

	/**
	 * @return total order
	 */
	public double getTotal() {
		// TODO change from double to Currency
		double sum = 0;
		for (Suborder s : suborders) {
			sum += s.getTotal();
		}
		return sum;
	}

	/* autogenerated stuff */

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public BigDecimal getSum() {
		return sum;
	}

	public void setSum(BigDecimal sum) {
		this.sum = sum;
	}

	public String getAutor() {
		return autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public int getDiscount() {
		return discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	public int getTableNum() {
		return tableNum;
	}

	public void setTableNum(int tableNum) {
		this.tableNum = tableNum;
	}

	public boolean isReadOnly() {
		return readOnly;
	}

	public void setReadOnly(boolean readOnly) {
		this.readOnly = readOnly;
	}

	public boolean isType() {
		return type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

	public Date getWorkingDate() {
		return workingDate;
	}

	public void setWorkingDate(Date workingDate) {
		this.workingDate = workingDate;
	}

	public Long getWorkShift() {
		return workShift;
	}

	public void setWorkShift(Long workShift) {
		this.workShift = workShift;
	}

	public int getNomerok() {
		return nomerok;
	}

	public void setNomerok(int nomerok) {
		this.nomerok = nomerok;
	}

	public BigDecimal getPayed() {
		return payed;
	}

	public void setPayed(BigDecimal payed) {
		this.payed = payed;
	}

	public boolean isCard() {
		return isCard;
	}

	public void setCard(boolean isCard) {
		this.isCard = isCard;
	}

	public int getDailyId() {
		return dailyId;
	}

	public void setDailyId(int dailyId) {
		this.dailyId = dailyId;
	}

	public List<Suborder> getSuborders() {
		return suborders;
	}

	public void setSuborders(List<Suborder> suborders) {
		this.suborders = suborders;
	}

}
